### ISSUE TITLE
New parsing function isn't perfect

### ISSUE THREAD

**Issue by rocketeerbkw** [JakobOvrum/LuaIRC#1]
Seeing some errors with new parsing function

![Errors](http://content.screencast.com/users/rocketeerbkw/folders/Jing/media/2ab6d9b1-12eb-44e4-904e-31bac94ec8d6/2010-07-01_0308.png)

**Comment by JakobOvrum** [comment]
I fixed the new parsing function and run it through a proper test suite this time, sorry about that. Not sure what went into me when I pushed an almost untested replacement.

Your problems should be fixed with the two newest commits.

(Thanks for your contributions, by the way!)

**Comment by rocketeerbkw** [comment]
Thx, so far so good :)

I definitely like Lua over Tcl so I'll try to keep the contributions coming
