### ISSUE TITLE
Can't connect to irc.efnet.org

### ISSUE THREAD

**Issue by darkFunction** [JakobOvrum/LuaIRC#15]
lua: /usr/local/share/lua/5.2/irc/init.lua:137: Closing Link: xxxx.xxxx.com (Connection timed out)

Am I missing something?

I'm using Lua 5.2

**Comment by ShadowNinja** [comment]
This is too vague. Was the nick is use or erroneous? If so that has been fixed.
Otherwise try adding this:

``` lua
function debugHook(line)
    print(line)
end
conn:hook("OnRaw", debugHook)
conn:hook("OnSend", debugHook)
```

**Comment by darkFunction** [comment]
Thanks- I guess the nick must have been the problem, it seems to be working now.  The debug hooks are very useful- I didn't know about that.
