### ISSUE TITLE
Pass mode options to the OnModeChange hook and fix access changing.

### ISSUE THREAD

**Issue by ShadowNinja** [JakobOvrum/LuaIRC#8]
Unless I missed something, mode options(such as a hostmask), for those modes that use them(o, and b for example) are not passed to the OnModeChange hook. Also, it seems that if a user's access changes(voiced or oped) the change is not recorded in the user list.

**Comment by ShadowNinja** [comment]
I have added this and more to my fork, if you are interested.

**Comment by JakobOvrum** [comment]
Of course; I'd love to see a pull request :)

**Comment by ShadowNinja** [comment]
@JakobOvrum: #9.
